<?php
function fivestar_custom_render_init(){
    global $base_path;
    global $base_url;
    
    $my_base_path = $GLOBALS['base_url'] . $GLOBALS['base_path'];

    $my_path = drupal_get_path('module', 'fivestar_custom_render');

    $my_settings = array(
         'basePath' => $GLOBALS['base_path'].$my_path.'/img/',
       );

    drupal_add_js(array('fivestar_custom_render' => $my_settings), 'setting');
}

function fivestar_custom_render_views_pre_render(&$view){
    switch ($view->name) {
        case 'get_reviews_for_node':
            //  override the global custom text field value

            if(count($view->result) > 0){


                // dpm($view->field['field_ambience']->view->result[0]->field_field_ambience[0]['raw']['average']);
                $set_average = 0;

                for($i = 0; $i < count($view->result); $i++){

                    $average = _get_average_for_review_view($view, $i);

                    $set_average += $average;
                    // dpm($average);
                    // dpm($view);
                    variable_set('fivestar_custom_render_average', $set_average);

                    $view->field['field_rate_the_resaurant']
                        ->view->result[$i]
                        ->field_field_rate_the_resaurant[0]
                    ['rendered']['average']['#rating'] = $average;

                    // $view->field['field_rate_the_resaurant']
                    //     ->view->result[1]
                    //     ->field_field_rate_the_resaurant[0]
                    // ['rendered']['average']['#rating'] = 100;

                }
            }


            break;
    }
}

function _get_average_for_review_view($view, $index){


        $ambience = $view->result[$index]->field_field_ambience[0]['raw']['average'];

        $food = $view->result[$index]->field_field_food[0]['raw']['average'];

        $average = ($ambience + $food)/2;

        return $average;    
}

// function _fivestar_custom_render_restaurant_star_html(){
//     cache_clear_all();
//     // dpm($node);
//     dpm(variable_get('fivestar_custom_render_average'));

//    $rating_average_of_restaurant = variable_get('fivestar_custom_render_average');

//    $final_average = ($rating_average_of_restaurant * 5)/100;

//    variable_del('fivestar_custom_render_average');

//    drupal_add_js(array('fivestar_custom_render' => array('rating_average_of_restaurant' => $final_average),), 'setting');
   
//    $render_array = array(
//   '#type' => 'container',
//   '#attributes' => array('id' => array('show_restaurant_page_rating')),
//   'child_element' => array(
//     '#markup' => t(''),
//   )
// );
// $node->content['fivestar_custom_render_restaurant_star_html'] = $render_array;
// return render($node->content['fivestar_custom_render_restaurant_star_html']);
// }


// function fivestar_custom_render_node_view($node, $view_mode, $langcode){
//     if($view_mode == 'full') {
    
//         dpm($node);

//         // $node->content['field_rating_of_the_restaurant'][0]['vote']['#values']['average'] = 100;

//         // $node->content['field_rating_of_the_restaurant']['#items'][0]['average'] = 100;
//         $node->field_rating_of_the_restaurant[$node->language][0]['value'] = 100;

        
//     }
// }


// function fivestar_custom_render_node_view_alter(&$build){

//     dpm($build['field_rating_of_the_restaurant']);

//     $build['field_rating_of_the_restaurant']['#items'][0]['average'] = 100;

//     $build['#object']->field_rating_of_the_restaurant['und'][0]['average'] = 100;


// }

